---

dependencies:

  - role: debops.php5
    php5_packages: '{{ wordpress_php5_packages }}'
    php5_pools: [ '{{ wordpress_php5_pool }}' ]
    when: wordpress_dependencies is defined and wordpress_dependencies
    tags: [ 'mysql', 'wordpress' ]

  - role: debops.nginx
    nginx_pki: '{{ wordpress_nginx_pki }}'
    nginx_webroot_create: False
    nginx_servers: [ '{{ wordpress_varnish_server }}', '{{ wordpress_backend_server }}' ]
    nginx_upstreams: [ '{{ wordpress_php_upstream }}', '{{ wordpress_varnish_upstream }}' ]
    when: wordpress_dependencies is defined and wordpress_dependencies
    tags: [ 'mysql', 'wordpress', 'nginx' ]

  - role: debops.redis

  - role: debops.secret

  - role: hhvm
    when: wordpress_dependencies is defined and wordpress_dependencies

  - role: mariadb
    when: wordpress_dependencies is defined and wordpress_dependencies
    tags: [ 'mysql', 'wordpress' ]

    mariadb_databases:
      - name: '{{ wordpress_database_name }}'
        state: 'present'

    mariadb_users:
      - name: '{{ wordpress_database_username }}'
        password: '{{ wordpress_database_password }}'
        host: '{{ wordpress_database_hostname }}'
        priv: '{{ wordpress_database_name }}.*:ALL'
        state: 'present'

  - role: varnish
    varnish_listen: '{{ wordpress_varnish_listen }}'
    varnish_backend_port: '{{ wordpress_varnish_backend_port }}'
    varnish_normalize_query_parameters: False
    varnish_purge_allow: '{{ wordpress_varnish_purge_allow }}'
    varnish_vcl_recv_conditions: '{{ wordpress_varnish_vcl_recv_conditions }}'
    varnish_vcl_recv_remove_cookies: '{{ wordpress_varnish_vcl_recv_remove_cookies }}'
    varnish_vcl_backend_response_conditions: '{{ wordpress_varnish_vcl_backend_response_conditions }}'
    when: wordpress_dependencies is defined and wordpress_dependencies

  - role: wpcli
