---

# ---- Install and configure WordPress ----

- name: Create WordPress directory
  file:
    path: '{{ wordpress_root }}'
    state: 'directory'
    owner: '{{ wordpress_user }}'
    group: '{{ wordpress_group }}'
    mode: '0755'
  when: wordpress_install_enabled

- name: Configure wp-cli
  template:
    src: 'var/www/wp-cli.local.yml.j2'
    dest: '{{ wordpress_root }}/wp-cli.local.yml'
    owner: '{{ wordpress_user }}'
    group: '{{ wordpress_group }}'
    mode: '0644'
  when: wordpress_install_enabled

- name: Check if WordPress is installed
  command: 'wp core is-installed'
  become_user: '{{ wordpress_user }}'
  args:
    chdir: '{{ wordpress_root }}'
  register: wordpress_installed
  changed_when: False
  failed_when: False
  when: wordpress_install_enabled

- name: Download WordPress
  command: 'wp core download'
  become_user: '{{ wordpress_user }}'
  args:
    chdir: '{{ wordpress_root }}'
    creates: '{{ wordpress_root }}/index.php'
  when: wordpress_installed is defined and wordpress_installed.rc == 1 and wordpress_install_enabled

- name: Configure WordPress
  command: 'wp core config --dbhost="{{ wordpress_database_host }}" --dbname="{{ wordpress_database_name }}" --dbuser="{{ wordpress_database_user }}" --dbpass="{{ wordpress_database_password }}" --dbprefix="{{ wordpress_table_prefix }}"'
  become_user: '{{ wordpress_user }}'
  args:
    chdir: '{{ wordpress_root }}'
    creates: '{{ wordpress_root }}/wp-config.php'
  when: wordpress_installed is defined and wordpress_installed.rc == 1 and wordpress_install_enabled

- name: Install WordPress
  command: 'wp core install --title="{{ wordpress_title }}" --admin_user="{{ wordpress_admin_username }}" --admin_password="{{ wordpress_admin_password }}" --admin_email="{{ wordpress_admin_email }}"'
  become_user: '{{ wordpress_user }}'
  args:
    chdir: '{{ wordpress_root }}'
  when: ((wordpress_installed is defined and wordpress_installed.rc == 1) and
         (wordpress_multisite is defined and not wordpress_multisite)) and wordpress_install_enabled

- name: Install WordPress Multisite
  command: 'wp core multisite-install --base="{{ wordpress_multisite_path }}" {{ "--subdomains" if wordpress_multisite_subdomains else "" }} --title="{{ wordpress_title }}" --admin_user="{{ wordpress_admin_username }}" --admin_password="{{ wordpress_admin_password }}" --admin_email="{{ wordpress_admin_email }}"'
  become_user: '{{ wordpress_user }}'
  args:
    chdir: '{{ wordpress_root }}'
  when: ((wordpress_installed is defined and wordpress_installed.rc == 1) and
         (wordpress_multisite is defined and wordpress_multisite)) and wordpress_install_enabled

- name: Schedule regular calls to wp-cron.php
  cron:
    name: 'Call wp-cron.php at {{ wordpress_domain }}'
    job: 'curl {{ "-k https" if wordpress_ssl|d() else "http" }}://{{ wordpress_domain }}{{ wordpress_cron_path }} > /dev/null 2>&1'
    user: '{{ wordpress_user }}'
    cron_file: '{{ wordpress_domain | replace(".", "_") }}'

- include: manage_plugins.yml
  tags: [ 'role::wordpress:plugins' ]
  when: wordpress_install_enabled

- include: manage_ssl.yml
  tags: [ 'role::wordpress:ssl' ]
  when: wordpress_ssl
